package com.rce.complaint_box.model.enums;

public enum ResponseCode {
    USER_NOT_FOUND, INVALID_CREDENTIALS, LOGIN_SUCCESS, USERNAME_ALREADY_TAKEN, ERROR, SUCCESS, CONFLICT,
    VALIDATION_ERROR, CONFLICT_USERNAME, CONFLICT_EMAIL, CONFLICT_EMPLOYEEID, CONFLICT_ROLLNUMBER, DELETED,
    USER_DELETED, EMPTY_FILE, UNAUTHORIZED, FILE_NOT_FOUND, NOT_FOUND, CONFLICT_MENTOR_ASSIGNMENT, INVALID_DEPARTMENT

}
