spring.application.name=complaint-box

frontend-url=${FRONTEND_URL:http://localhost:5173}
backend-url=${BACKEND_URL:http://localhost:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/complaint_box}

jwt-secret=${JWT_SECRET:ZEdlZTJnSlRHLUtDLi5xQUx7MFR5S3RNZk03JSt4enJkLF8mZUp4WntmJTJGYWVQNmo=}
jwt-expiry=${JWT_EXPIRY:604800000}

file-storage-directory=${FILE_STORAGE_DIR:${user.dir}/../files}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB